### ISSUE TITLE
Video Not Sending

### ISSUE THREAD

**Issue by deeneshchowdhary** [DeligenceTechnologies/Intruder-detector-with-Raspberry-Pi-and-Pushbullet#1]
**TypeError: not all arguments converted during string formatting
Logged from file motion_main.py, line 92**

I am getting above error after running motion_main.py and video is not sending.

**Comment by pawan-deligence** [comment]
Hi that error you will get but it will send video and image as well in your smartphone. You have to make sure that you are using the correct access token, which you will get in pushbullet settings.

**Comment by deeneshchowdhary** [comment]
Thank you Pawan! I believe I am using correct token because I was able to receive first image and after that I did not receive any video.
